theme = "modest"
baseURL = "https://example.com"
languageCode = "en-us"
title = "Modest example site"

[params]
    description = ""
    github = "https://examplesite.com"
    linkedin = "https://examplesite.com"
    twitter = "https://examplesite.com"

